version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: health-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: health_db
    ports:
      - "3307:3306"
    volumes:
      - health_mysql_data:/var/lib/mysql
      - ./init_health.sql:/docker-entrypoint-initdb.d/init_health.sql
    restart: unless-stopped

volumes:
  health_mysql_data:
